/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.scientific.project;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.*;

/**
 *
 * @author SUNNY
 */
public class Default extends javax.swing.JFrame{

    /**
     * Creates new form Default
     */
    //JFrame f;
    public Default() {
        initComponents(); 
        //f=new JFrame("Standard Calculator");
        ImageIcon ic=new ImageIcon("src\\calc\\arrow.jpg");
        ImageIcon mulic=new ImageIcon("src\\calc\\cross2.jpg");
        bback.setIcon(ic);
        bmul.setIcon(mulic);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scientific = new javax.swing.JButton();
        standard = new javax.swing.JButton();
        converter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        bpanel = new javax.swing.JPanel();
        bdiv = new javax.swing.JButton();
        bce = new javax.swing.JButton();
        bc = new javax.swing.JButton();
        bback = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bminus = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bplus = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        bequal = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basic");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        scientific.setBackground(new java.awt.Color(0, 0, 0));
        scientific.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        scientific.setForeground(new java.awt.Color(153, 153, 153));
        scientific.setText("Scientific");
        scientific.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scientific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scientificActionPerformed(evt);
            }
        });

        standard.setBackground(new java.awt.Color(0, 0, 0));
        standard.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        standard.setForeground(new java.awt.Color(153, 153, 153));
        standard.setText("Standard");
        standard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardActionPerformed(evt);
            }
        });

        converter.setBackground(new java.awt.Color(0, 0, 0));
        converter.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        converter.setForeground(new java.awt.Color(153, 153, 153));
        converter.setText("Converter");
        converter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        converter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t1.setBackground(new java.awt.Color(51, 51, 51));
        t1.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        bpanel.setBackground(new java.awt.Color(0, 0, 0));
        bpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bdiv.setBackground(new java.awt.Color(51, 51, 51));
        bdiv.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bdiv.setForeground(new java.awt.Color(255, 255, 255));
        bdiv.setText("/");
        bdiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });

        bce.setBackground(new java.awt.Color(51, 51, 51));
        bce.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bce.setForeground(new java.awt.Color(255, 255, 255));
        bce.setText("CE");
        bce.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bceActionPerformed(evt);
            }
        });

        bc.setBackground(new java.awt.Color(51, 51, 51));
        bc.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bc.setForeground(new java.awt.Color(255, 255, 255));
        bc.setText("C");
        bc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcActionPerformed(evt);
            }
        });

        bback.setBackground(new java.awt.Color(51, 51, 51));
        bback.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bback.setForeground(new java.awt.Color(255, 255, 255));
        bback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(51, 51, 51));
        b7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("7");
        b7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(51, 51, 51));
        b8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("8");
        b8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(51, 51, 51));
        b9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("9");
        b9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        bmul.setBackground(new java.awt.Color(51, 51, 51));
        bmul.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bmul.setForeground(new java.awt.Color(255, 255, 255));
        bmul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(51, 51, 51));
        b4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("4");
        b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(51, 51, 51));
        b5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("5");
        b5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(51, 51, 51));
        b6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("6");
        b6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        bminus.setBackground(new java.awt.Color(51, 51, 51));
        bminus.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bminus.setForeground(new java.awt.Color(255, 255, 255));
        bminus.setText("-");
        bminus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bminusActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(51, 51, 51));
        b1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(51, 51, 51));
        b2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("2");
        b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(51, 51, 51));
        b3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("3");
        b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        bplus.setBackground(new java.awt.Color(51, 51, 51));
        bplus.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bplus.setForeground(new java.awt.Color(255, 255, 255));
        bplus.setText("+");
        bplus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bplusActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(51, 51, 51));
        b0.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        b0.setForeground(new java.awt.Color(255, 255, 255));
        b0.setText("0");
        b0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        bdot.setBackground(new java.awt.Color(51, 51, 51));
        bdot.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bdot.setForeground(new java.awt.Color(255, 255, 255));
        bdot.setText(".");
        bdot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });

        bequal.setBackground(new java.awt.Color(51, 51, 51));
        bequal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        bequal.setForeground(new java.awt.Color(255, 255, 255));
        bequal.setText("=");
        bequal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bequalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bpanelLayout = new javax.swing.GroupLayout(bpanel);
        bpanel.setLayout(bpanelLayout);
        bpanelLayout.setHorizontalGroup(
            bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bpanelLayout.createSequentialGroup()
                        .addGroup(bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bpanelLayout.createSequentialGroup()
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bdot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bpanelLayout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bplus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bequal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bpanelLayout.createSequentialGroup()
                        .addComponent(bce, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bback, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bpanelLayout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bpanelLayout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bminus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bpanelLayout.setVerticalGroup(
            bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bback, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bce, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bminus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bplus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bequal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        t2.setBackground(new java.awt.Color(51, 51, 51));
        t2.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
            .addComponent(bpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(bpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(327, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(standard, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scientific, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(converter, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scientific, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(converter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standard, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
        // TODO add your handling code here:
       String s=t1.getText();
       String s2=t2.getText();
       if(s2.length()!=0)
       {
           t1.setText(s2);
           t2.setText("");
       }
       int last=s.length();
       char ch;
       //JOptionPane.showMessageDialog(null,last);
       if(s.length()!=0)
       {
        ch=s.charAt(last-1);
        if(ch=='/')
        {
           //JOptionPane.showMessageDialog(null,s.charAt(s.lastIndexOf(s)));
           t1.setText(s);
        }
        else if((ch=='-')||(ch=='+')||(ch=='*'))
        {
           s=s.substring(0,last-1);
           t1.setText(s+"/");
        }
           //t1.setText(t1.getText()+"+");
        else
           t1.setText(t1.getText()+"/");       
       }
       else if(s.length()==0)
           t1.setText(s);
    }//GEN-LAST:event_bdivActionPerformed

    private void standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardActionPerformed
        // TODO add your handling code here:
        Default d=new Default();
        d.setSize(512,512);
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_standardActionPerformed

    private void scientificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scientificActionPerformed
        // TODO add your handling code here:
        Scientific sc=new Scientific();
        sc.setVisible(true);
        sc.setSize(600,600);
        dispose();
    }//GEN-LAST:event_scientificActionPerformed

    private void bceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bceActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        //JOptionPane.showMessageDialog(rootPane,s);
        if(s.length()==0)
            t1.setText(s);
        else if((s.contains("+"))||(s.contains("-"))||(s.contains("*"))||(s.contains("/")))
        {
            int plast=s.lastIndexOf("+");
            int milast=s.lastIndexOf("-");
            int mulast=s.lastIndexOf("*");
            int dlast=s.lastIndexOf("/");            
            int []a={-1,-1,-1,-1};
            a[0]=plast;
            a[1]=milast;
            a[2]=mulast;
            a[3]=dlast;
            Arrays.sort(a);
            if((s.charAt(s.length()-1)=='+')||(s.charAt(s.length()-1)=='-')||(s.charAt(s.length()-1)=='*')||(s.charAt(s.length()-1)=='/'))
            {
                t1.setText(s.substring(0,s.length()-1));
                //JOptionPane.showMessageDialog(rootPane,s);
            }
            else if((s.indexOf("+")==-1)&&(s.indexOf("-")==-1)&&(s.indexOf("*")==-1)&&(s.indexOf("/")==-1))
            {
                t1.setText("");
                //JOptionPane.showMessageDialog(rootPane,s);
            }
            else
            {
                t1.setText(s.substring(0,a[3]+1));
                //JOptionPane.showMessageDialog(rootPane,s);
            }
        }
        else if((s.indexOf("+")==-1)&&(s.indexOf("-")==-1)&&(s.indexOf("*")==-1)&&(s.indexOf("/")==-1))
        {
            t1.setText("");
            //JOptionPane.showMessageDialog(rootPane,s);
        }
    }//GEN-LAST:event_bceActionPerformed

    private void bcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcActionPerformed
        // TODO add your handling code here:
        t1.setText("");
    }//GEN-LAST:event_bcActionPerformed

    private void bbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        if(s.length()==0)
            t1.setText(s);
        else if(s.length()>0)
        {
            s=s.substring(0,s.length()-1);
            t1.setText(s);
        }
    }//GEN-LAST:event_bbackActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
         String s=t1.getText();
        String s2=t2.getText();
        //JOptionPane.showMessageDialog(rootPane,s2.length());
        if(("0.0".equals(s))||(s.length()==0)||(s2.length()!=0))
        {
            if(s.length()!=0)
            {
                char ch=s.charAt(s.length()-1);
                if((ch=='+')||(ch=='-')||(ch=='*')||(ch=='/'))
                {
                       t1.setText(s+b7.getText());
                }
                else if(ch=='.')
                {
                    t1.setText(s+b7.getText());
                }
                else 
                {
                        t1.setText(b7.getText());
                        t2.setText("");
                }
            }
            else
                t1.setText(s+b7.getText());
        }
        else
            t1.setText(s+b7.getText());  
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String s2=t2.getText();
        //JOptionPane.showMessageDialog(rootPane,s2.length());
        if(("0.0".equals(s))||(s.length()==0)||(s2.length()!=0))
        {
            if(s.length()!=0)
            {
                char ch=s.charAt(s.length()-1);
                if((ch=='+')||(ch=='-')||(ch=='*')||(ch=='/'))
                {
                       t1.setText(s+b8.getText());
                }
                else if(ch=='.')
                {
                    t1.setText(s+b8.getText());
                }
                else 
                {
                        t1.setText(b8.getText());
                        t2.setText("");
                }
            }
            else
            t1.setText(s+b8.getText());
        }
        else
            t1.setText(s+b8.getText());
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String s2=t2.getText();
        //JOptionPane.showMessageDialog(rootPane,s2.length());
        if(("0.0".equals(s))||(s.length()==0)||(s2.length()!=0))
        {
            if(s.length()!=0)
            {
                char ch=s.charAt(s.length()-1);
                if((ch=='+')||(ch=='-')||(ch=='*')||(ch=='/'))
                {
                       t1.setText(s+b9.getText());
                }
                else if(ch=='.')
                {
                    t1.setText(s+b9.getText());
                }
                else 
                {
                        t1.setText(b9.getText());
                        t2.setText("");
                }
            }
            else
            t1.setText(s+b9.getText());
        }
        else
            t1.setText(s+b9.getText());
    }//GEN-LAST:event_b9ActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
        // TODO add your handling code here:
       String s=t1.getText();
       String s2=t2.getText();
       if(s2.length()!=0)
       {
           t1.setText(s2);
           t2.setText("");
       }
       int last=s.length();
       char ch;
       //JOptionPane.showMessageDialog(null,last);
       if(s.length()!=0)
       {
        ch=s.charAt(last-1);
        if(ch=='*')
        {
           //JOptionPane.showMessageDialog(null,s.charAt(s.lastIndexOf(s)));
           t1.setText(s);
        }
        else if((ch=='-')||(ch=='+')||(ch=='/'))
        {
           s=s.substring(0,last-1);
           t1.setText(s+"*");
        }
           //t1.setText(t1.getText()+"+");
        else
           t1.setText(t1.getText()+"*");       
       }
       else if(s.length()==0)
           t1.setText(s);
    }//GEN-LAST:event_bmulActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String s2=t2.getText();
        //JOptionPane.showMessageDialog(rootPane,s2.length());
        if(("0.0".equals(s))||(s.length()==0)||(s2.length()!=0))
        {
            if(s.length()!=0)
            {
                char ch=s.charAt(s.length()-1);
                if((ch=='+')||(ch=='-')||(ch=='*')||(ch=='/'))
                {
                       t1.setText(s+b4.getText());
                }
                else if(ch=='.')
                {
                    t1.setText(s+b4.getText());
                }
                else 
                {
                        t1.setText(b4.getText());
                        t2.setText("");
                }
            }
            else
            t1.setText(s+b4.getText());
        }
        else
            t1.setText(s+b4.getText());
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String s2=t2.getText();
        //JOptionPane.showMessageDialog(rootPane,s2.length());
        if(("0.0".equals(s))||(s.length()==0)||(s2.length()!=0))
        {
            if(s.length()!=0)
            {
                char ch=s.charAt(s.length()-1);
                if((ch=='+')||(ch=='-')||(ch=='*')||(ch=='/'))
                {
                       t1.setText(s+b5.getText());
                }
                else if(ch=='.')
                {
                    t1.setText(s+b5.getText());
                }
                else 
                {
                        t1.setText(b5.getText());
                        t2.setText("");
                }
            }
            else
            t1.setText(s+b5.getText());
        }
        else
            t1.setText(s+b5.getText());
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String s2=t2.getText();
        //JOptionPane.showMessageDialog(rootPane,s2.length());
        if(("0.0".equals(s))||(s.length()==0)||(s2.length()!=0))
        {
            if(s.length()!=0)
            {
                char ch=s.charAt(s.length()-1);
                if((ch=='+')||(ch=='-')||(ch=='*')||(ch=='/'))
                {
                       t1.setText(s+b6.getText());
                }
                else if(ch=='.')
                {
                    t1.setText(s+b6.getText());
                }
                else 
                {
                        t1.setText(b6.getText());
                        t2.setText("");
                }
            }
            else
            t1.setText(s+b6.getText());
        }
        else
            t1.setText(s+b6.getText());
    }//GEN-LAST:event_b6ActionPerformed

    private void bminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bminusActionPerformed
        // TODO add your handling code here:
       String s=t1.getText();
       String s2=t2.getText();
       if(s2.length()!=0)
       {
           t1.setText(s2);
           t2.setText("");
       }
       int last=s.length();
       char ch;
       //JOptionPane.showMessageDialog(null,last);
       if(s.length()!=0)
       {
        ch=s.charAt(last-1);
        if(ch=='-')
        {
           //JOptionPane.showMessageDialog(null,s.charAt(s.lastIndexOf(s)));
           t1.setText(s);
        }
        else if((ch=='/')||(ch=='+')||(ch=='*'))
        {
           s=s.substring(0,last-1);
           t1.setText(s+"-");
        }
           //t1.setText(t1.getText()+"+");
        else
           t1.setText(t1.getText()+"-");       
       }
       else if(s.length()==0)
           t1.setText(s+bminus.getText());
    }//GEN-LAST:event_bminusActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String s2=t2.getText();
        //JOptionPane.showMessageDialog(rootPane,s2.length());
        if(("0.0".equals(s))||(s.length()==0)||(s2.length()!=0))
        {
            if(s.length()!=0)
            {
                char ch=s.charAt(s.length()-1);
                if((ch=='+')||(ch=='-')||(ch=='*')||(ch=='/'))
                {
                       t1.setText(s+b1.getText());
                }
                else if(ch=='.')
                {
                    t1.setText(s+b1.getText());
                }
                else 
                {
                        t1.setText(b1.getText());
                        t2.setText("");
                }
            }
            else
            t1.setText(s+b1.getText());
        }
        else
            t1.setText(s+b1.getText());
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String s2=t2.getText();
        //JOptionPane.showMessageDialog(rootPane,s2.length());
        if(("0.0".equals(s))||(s.length()==0)||(s2.length()!=0))
        {
            if(s.length()!=0)
            {
                char ch=s.charAt(s.length()-1);
                if((ch=='+')||(ch=='-')||(ch=='*')||(ch=='/'))
                {
                       t1.setText(s+b2.getText());
                }
                else if(ch=='.')
                {
                    t1.setText(s+b2.getText());
                }
                else 
                {
                        t1.setText(b2.getText());
                        t2.setText("");
                }
            }
            else
            t1.setText(s+b2.getText());
        }
        else
            t1.setText(s+b2.getText());
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String s2=t2.getText();
        //JOptionPane.showMessageDialog(rootPane,s2.length());
        if(("0.0".equals(s))||(s.length()==0)||(s2.length()!=0))
        {
            if(s.length()!=0)
            {
                char ch=s.charAt(s.length()-1);
                if((ch=='+')||(ch=='-')||(ch=='*')||(ch=='/'))
                {
                       t1.setText(s+b3.getText());
                }
                else if(ch=='.')
                {
                    t1.setText(s+b3.getText());
                }
                else 
                {
                        t1.setText(b3.getText());
                        t2.setText("");
                }
            }
            else
                t1.setText(s+b3.getText());
        }
        else
            t1.setText(s+b3.getText());
    }//GEN-LAST:event_b3ActionPerformed

    private void bplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bplusActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String s2=t2.getText();
        if(s2.length()!=0)
        {
            t1.setText(t2.getText());
            t2.setText("");
        }
       int last=s.length();
       char ch;
       //JOptionPane.showMessageDialog(null,last);
       if(s.length()!=0)
       {
        ch=s.charAt(last-1);
        if(ch=='+')
        {
           //JOptionPane.showMessageDialog(null,s.charAt(s.lastIndexOf(s)));
           t1.setText(s);
        }
        else if((ch=='-')||(ch=='/')||(ch=='*'))
        {
           s=s.substring(0,last-1);
           t1.setText(s+"+");
        }
           //t1.setText(t1.getText()+"+");
        else
           t1.setText(t1.getText()+"+");       
       }
       else if(s.length()==0)
           t1.setText(s);
    }//GEN-LAST:event_bplusActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String s2=t2.getText();
        //JOptionPane.showMessageDialog(rootPane,s2.length());
        if(("0.0".equals(s))||(s.length()==0)||(s2.length()!=0))
        {
            if(s.length()!=0)
            {
                char ch=s.charAt(s.length()-1);
                if((ch=='+')||(ch=='-')||(ch=='*')||(ch=='/'))
                {
                       t1.setText(s+b0.getText());
                }
                else if(ch=='.')
                {
                    t1.setText(s+b0.getText());
                }
                else 
                {
                        t1.setText(b0.getText());
                        t2.setText("");
                }
            }
            else
                t1.setText(s+b0.getText());
        }
        else
            t1.setText(s+b0.getText());
    }//GEN-LAST:event_b0ActionPerformed

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdotActionPerformed
        String s=t1.getText();
        int plus,minus,mul,div,plast,milast,mulast,dlast;
        plus=minus=mul=div=plast=milast=mulast=dlast=-1;
        plus=s.indexOf("+");
        //JOptionPane.showMessageDialog(rootPane, plus+"Plus");
        minus=s.indexOf("-");
        //JOptionPane.showMessageDialog(rootPane, minus+"Minus");
        mul=s.indexOf("*");
        //JOptionPane.showMessageDialog(rootPane, mul+"Mul");
        div=s.indexOf("/");
        //JOptionPane.showMessageDialog(rootPane, div+"Div");
        plast=s.lastIndexOf("+");
        //JOptionPane.showMessageDialog(rootPane, plast+"plast");
        milast=s.lastIndexOf("-");
        //JOptionPane.showMessageDialog(rootPane, milast+"milast");
        mulast=s.lastIndexOf("*");
        //JOptionPane.showMessageDialog(rootPane, mulast+"mulast");
        dlast=s.lastIndexOf("/");
        //JOptionPane.showMessageDialog(rootPane, dlast+"dlast");
        int []a={0,0,0,0};                
        a[0]=plast;
        a[1]=milast;
        a[2]=mulast;
        a[3]=dlast;
        //for(int i=0;i<a.length;i++)
            //JOptionPane.showMessageDialog(rootPane, (a[i]+" a"+i));
        Arrays.sort(a);
        //for(int i=0;i<a.length;i++)
            //JOptionPane.showMessageDialog(rootPane, (a[i]+" a"+i));
        //JOptionPane.showMessageDialog(rootPane, a);
        //JOptionPane.showMessageDialog(rootPane,a[3]+"OP Index");
        //JOptionPane.showMessageDialog(rootPane,s.lastIndexOf(".")+"Dot last");
        if(s.length()==0)
        {
            t1.setText(".");
        }
        else if(s.indexOf('.')==-1)
        {
            t1.setText(s+".");
        }        
        else if(a[a.length-1]>s.lastIndexOf("."))
        {
            t1.setText(s+bdot.getText());
        }
    }//GEN-LAST:event_bdotActionPerformed

    private void bequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bequalActionPerformed
        // TODO add your handling code here:
        String s=t1.getText();
        String exp="";
        ScriptEngineManager mgr=new ScriptEngineManager();
        ScriptEngine engine=mgr.getEngineByName("JavaScript");
        try {
            if(s.length()==0)
            {
                JOptionPane.showMessageDialog(null,"Enter Values to Calculate");
            }
            else
            {
                 if((s.charAt(s.length()-1)=='/')||(s.charAt(s.length()-1)=='*')||(s.charAt(s.length()-1)=='-')||(s.charAt(s.length()-1)=='+'))
                 {
                    JOptionPane.showMessageDialog(null,"Too few arguments passed to operator for calculation");
                 }
                 else
                 {
                    exp=engine.eval(t1.getText()).toString();
                    BigDecimal b=new BigDecimal(exp);
                    b=b.setScale(2, RoundingMode.UP);
                    if(("Infinity".equals(exp))||("-Infinity".equals(exp))||("Nan".equals(exp))||(s.charAt(s.length()-1)=='.'))
                    {   
                        JOptionPane.showMessageDialog(null,"You are Performed Invalid Operation");
                        t1.setText("");
                    }            
               
                    else
                    {
                        //exp=engine.eval(t1.getText()).toString();
                        t2.setText(b.toString());
                    }
                 }
            }
        } 
        catch (ScriptException ex)
        {
            JOptionPane.showMessageDialog(rootPane,"Invalid Expression");
            t1.setText("");
            //Logger.getLogger(Default.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bequalActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void converterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterActionPerformed
        // TODO add your handling code here:
        Converter c=new Converter();
        c.setSize(512,512);
        c.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_converterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Default.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Default.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Default.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Default.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Default().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bback;
    private javax.swing.JButton bc;
    private javax.swing.JButton bce;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bequal;
    private javax.swing.JButton bminus;
    private javax.swing.JButton bmul;
    private javax.swing.JPanel bpanel;
    private javax.swing.JButton bplus;
    private javax.swing.JButton converter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton scientific;
    private javax.swing.JButton standard;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
